local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', "<cmd>Telescope find_files<cr>", {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', '<cmd>Telescope live_grep<cr>', {})
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
